### ISSUE TITLE
Websocket RESETVAL, LENGTHVAR and LASTCHANGEVAR are missing in the specification

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#159] opened 2015-06-22 18:07 UTC
*LOL*

**Comment by grodansparadis** [comment] 2015-06-23 12:49
Fixed. writevar and restevar now return type and value.

**Comment by BlueAndi** [comment] 2015-06-23 18:50
Great Ake, thanks. I will update the library accordingly. Did you update the demoserver too? I use it at the moment for testing purposes. And btw. the demosever is REALLY helpful!!!! Like it a lot. And my PC nodes now makes a lot more sense, as I connect them there too.

**Comment by grodansparadis** [comment] 2015-06-23 20:49
Hi,

yes I updated the demoserver also. Not tested anything though so let me know if something went wrong. Well I know you will!   Good that it comes to use.

**Comment by BlueAndi** [comment] 2015-06-24 18:37
Hi Ake,
my tests shows the following:
20:35:23.383 Cmd: C;RESETVAR;DEMOVARIABLE
20:35:23.500 Rsp: +;RESETVAR;DEMOVARIABLE;2;false
20:35:32.408 Cmd: C;WRITEVAR;DEMOVARIABLE;true
20:35:32.524 Rsp: +;WRITEVAR

RESETVAR is fine, but WRITEVAR responses nothing. Can you check please?

**Comment by grodansparadis** [comment] 2015-06-24 18:59
Should be fixed now. Updated on demo server.

**Comment by BlueAndi** [comment] 2015-06-24 19:03
Not all ;-)

21:01:35.485 Cmd: C;WRITEVAR;DEMOVARIABLE;false
21:01:35.601 Rsp: +;WRITEVAR;false;2;false <--- Fine

21:01:41.719 Cmd: C;WRITEVAR;DEMOVARIABLE;asdfsadfasdf
21:01:41.835 Rsp: +;WRITEVAR;asdfsadfasdf;2;false <---- Wrong :-)

21:01:55.894 Cmd: C;READVAR;DEMOVARIABLE
21:01:56.130 Rsp: +;READVAR;DEMOVARIABLE;2;false

**Comment by grodansparadis** [comment] 2015-06-24 19:13
This is actually correct as "false" is the default. You will see the same for a numerical variable if you try to set it to a string it will be zero.  This is by design as I said but also feel like this maybe should be more strict when I see it now. But in the meanwhile...  I have tons of other stuff at the moment I must finish before a two week vacation. So this have to be later.

**Comment by BlueAndi** [comment] 2015-06-24 19:16
But "false" in this case is the persistency, take a look to the first parameter after WRITEVAR ... this is the value, which is "asdfsadfasdf".

**Comment by BlueAndi** [comment] 2015-06-24 19:26
Another example shows it again different.
Precondition, the variable is false and persistency is false.

Now set value to "true".
21:21:18.400 Cmd: C;WRITEVAR;DEMOVARIABLE;true
21:21:18.522 Rsp: +;WRITEVAR;true;2;true

Returns now true for the type too ... hmmm ...

Now set a invalid value:
21:21:25.801 Cmd: C;WRITEVAR;DEMOVARIABLE;asfsafdsadf
21:21:25.923 Rsp: +;WRITEVAR;asfsafdsadf;2;false

Returns the wrong value, the type and looks like the new value. Ahhhh ..... the value is returned now in the way that I see the written and the new value. Ok ... I understand ... that means the current specification is wrong ... or the other way around.

**Comment by BlueAndi** [comment] 2015-06-24 19:27
And ... take your time ... there is no need to fix that now.

**Comment by grodansparadis** [comment] 2015-06-24 19:31
A variable was overwritten.

Andreas Merkle skrev den 2015-06-24 21:16:
>
> But "false" in this case is the persistency, take a look to the first 
> parameter after WRITEVAR ... this is the value, which is "asdfsadfasdf".
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/159#issuecomment-114984716>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by grodansparadis** [comment] 2015-06-24 19:32
I am building on the demo server right now but must attend to other things now. Hopefully it works.

**Comment by BlueAndi** [comment] 2015-06-24 19:33
Thanks and as I said ... don't hurry ... no problem!

**Comment by grodansparadis** [comment] 2015-06-24 19:38
Built now.

Andreas Merkle skrev den 2015-06-24 21:26:
>
> Another example shows it again different.
> Precondition, the variable is false and persistency is false.
>
> Now set value to "true".
> 21:21:18.400 Cmd: C;WRITEVAR;DEMOVARIABLE;true
> 21:21:18.522 Rsp: +;WRITEVAR;true;2;true
>
> Returns now true for the type too ... hmmm ...
>
> Now set a invalid value:
> 21:21:25.801 Cmd: C;WRITEVAR;DEMOVARIABLE;asfsafdsadf
> 21:21:25.923 Rsp: +;WRITEVAR;asfsafdsadf;2;false
>
> Returns the wrong value, the type and looks like the new value. Ahhhh 
> ..... the value is returned now in the way that I see the written and 
> the new value. Ok ... I understand ... that means the current 
> specification is wrong ... or the other way around.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/159#issuecomment-114986525>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by BlueAndi** [comment] 2015-06-24 19:40
Great, works as expected!!

21:39:24.293 Cmd: C;WRITEVAR;DEMOVARIABLE;true
21:39:24.412 Rsp: +;WRITEVAR;DEMOVARIABLE;2;true

21:39:35.320 Cmd: C;WRITEVAR;DEMOVARIABLE;asdfasdf
21:39:35.152 Rsp: +;WRITEVAR;DEMOVARIABLE;2;false

**Closed** 2015-06-24 19:40 UTC
